### ISSUE TITLE
libfuse2 as dependency is missing in AppImage?

### ISSUE THREAD

**Issue by soysource** [SUNET/tugpgp#13]
Hi! 

I tried to follow this [User Guide](https://github.com/SUNET/tugpgp/wiki) and tried to excecute the AppImage on Ubuntu 22.04.2 LTS. 
Then I got the following error:
```
$ ./Tugpgp-0.1.2-x86_64.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
```

After I installed libfuse2 via apt, I could run the program.

**Comment by kushaldas** [comment]
@soysource Thank you for the issue. As the error message mentioned, we will add the instruction to install libfuse to the guide. That is a requirement for the AppImage itself.

**Comment by soysource** [comment]
@kushaldas Oh, I see now even in the very error message (>_<)! Sorry for the confusing title and thanks for updating!

**Comment by kushaldas** [comment]
We updated the documentation, closing the issue.
