### ISSUE TITLE
Import the generated public key

### ISSUE THREAD

**Issue by soysource** [SUNET/tugpgp#14]
Hi!

It would be really nice if the program handles even importing the public key to local keychain.   
Then I can skip running `gpg --import ${publickey}.pub` :) 
Thank you in advance!

**Comment by kushaldas** [comment]
After going through the list of running environments (mac/linux), I think there is no easy way to judge the current state of the `gpg` in those systems, so it is better that we keep the importing for the user. Which is also useful if you actually generating the key in an airgapped system. There we need to import the public key in a different machine than the machine key was generated.
